version: 0.2

phases:
  install:
    commands:
      - npm install
      - apt update && apt install -y awscli && apt -y autoremove
  build:
    commands:
      - echo "Installer build started on `date`"
      - npm run compile-win
  post_build:
    commands:
      - echo "Pushing artifacts"
      - aws s3 ls 
artifacts:
  type: zip
  files:
     - 'dist/*'
  discard-paths: yes