version: 0.2

phases:
  install:
    commands:
      - amazon-linux-extras install -y docker
  build:
    commands:
      - echo "Installer build started on `date`"
      - docker build .
  post_build:
    commands:
      - echo "Pushing artifacts"
      - aws s3 ls 
artifacts:
  type: zip
  files:
     - 'dist/*'
  discard-paths: yes